Smartspace: Fix SysUiStatsLog issue.
java.lang.NoSuchMethodError: No static method write(IIIIIIIIIIII)V in class Lcom/android/systemui/shared/system/SysUiStatsLog;

I'm not exactly sure, why SysUiStatsLog wasn't updated in our case. To get around
the problem, it is required to revert to an older blob prior to "SQ1D.211205.016.A1".

Signed-off-by: spezi77 <spezi7713@gmx.net>
Change-Id: I768b875ab4a5cd76730e962239ebb69e0d530fbf