audio codec: Fix a compiler error.
frameworks/base/media/java/android/media/AudioSystem.java:362: error: duplicate case label
            case SOURCE_CODEC_TYPE_OPUS: // TODO update in U

frameworks/base/packages/SettingsLib/src/com/android/settingslib/bluetooth/A2dpProfile.java:380: error: duplicate case label
            case SOURCE_CODEC_TYPE_OPUS: // TODO update in U

Signed-off-by: spezi77 <spezi7713@gmx.net>